---
layout: news_item
title: Improving Performance and Scalability
date: 2015-03-11 17:30:23
author: deepreef
---

I've slightly revised the data model to improve import performance, and also to make the model more scalable for large numbers of data objects (>> 2 billion). This also simplified the model and eliminated the superfluous UUIDs generated by BioGUID.org.
